<a href="https://colab.research.google.com/github/yaswanthdongara/modules/blob/main/operations_on_series_object_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
s=pd.Series([12,25,np.nan,pd.NA,None])
print("No.of missing values",s[s.isnull()].size)
print("No.of missing values",s.isnull().sum())
print("No.of missing values",s.isna().sum())
print("No.of missing values",s[s.isna()].size)

No.of missing values 3
No.of missing values 3
No.of missing values 3
No.of missing values 3


In [9]:
s=pd.Series([12,25,np.nan,pd.NA,None])
print("No.of missing values",s[s.notnull()].size)
print("No.of missing values",s.notnull().sum())
print("No.of missing values",s.notna().sum())
print("No.of missing values",s[s.notna()].size)
print(s[s.notna()])
print("-"*70)
print(s.notna())

No.of missing values 2
No.of missing values 2
No.of missing values 2
No.of missing values 2
0    12
1    25
dtype: object
----------------------------------------------------------------------
0     True
1     True
2    False
3    False
4    False
dtype: bool


In [24]:
#sort the series object values
import numpy as np
a=pd.Series([6, 1, 8, 5, 2, 8, 8, 6, 6])
print(a.values) #if .values is not used then index will also be printed
a.sort_values()
print(a.values)
print(a.sort_values().values)
a.sort_values(inplace=True) #index stays same
print(a)
a.sort_values(ascending=False,inplace=True)
print(a)


[6 1 8 5 2 8 8 6 6]
[6 1 8 5 2 8 8 6 6]
[1 2 5 6 6 6 8 8 8]
1    1
4    2
3    5
0    6
7    6
8    6
5    8
2    8
6    8
dtype: int64
2    8
5    8
6    8
0    6
7    6
8    6
3    5
4    2
1    1
dtype: int64


In [27]:
print(a.values[-1]) #smallest value when 'a' is sorted in descending order
print(a.min())
print(a.values[0]) #largest value when 'a' is sorted in descending order
print(a.max())

1
1
8
8


In [30]:
print(len(a))
print(a.unique())
print(a.nunique())

9
[8 6 5 2 1]
5


In [37]:
#frequency
print(a.values)
print(a.value_counts().values)
print("-"*70)
print(a.value_counts())

[8 8 8 6 6 6 5 2 1]
[3 3 1 1 1]
----------------------------------------------------------------------
8    3
6    3
5    1
2    1
1    1
Name: count, dtype: int64
