<a href="https://colab.research.google.com/github/yaswanthdongara/modules/blob/main/Sep_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [60]:
a = np.random.randint(1,10,size=9).reshape(3,3)
b = np.random.randint(1,10,size=9).reshape(3,3)
c = np.dot(a,b)
print(a)
print(b)
print(c)
d = a@b
print(d)

[[5 5 8]
 [4 5 9]
 [1 8 7]]
[[5 1 8]
 [8 6 1]
 [6 5 4]]
[[113  75  77]
 [114  79  73]
 [111  84  44]]
[[113  75  77]
 [114  79  73]
 [111  84  44]]


In [66]:
#inner product
a = np.random.randint(1,10,size=(3,3))
b = np.random.randint(1,10,size=(3,3))
c = np.inner(a,b)
d = np.dot(a,b)
print(a)
print(b)
print(c)
print(d)

[[8 7 4]
 [8 4 9]
 [7 4 7]]
[[9 5 4]
 [2 3 4]
 [4 8 2]]
[[123  53  96]
 [128  64  82]
 [111  54  74]]
[[102  93  68]
 [116 124  66]
 [ 99 103  58]]


In [68]:
a = np.random.randint(1,10,size=(2,2))
b = np.random.randint(1,10,size=(2,2))
c = np.outer(a,b)
print(a)
print(b)
print(c)

[[1 6]
 [7 6]]
[[5 6]
 [3 9]]
[[ 5  6  3  9]
 [30 36 18 54]
 [35 42 21 63]
 [30 36 18 54]]


In [5]:
#solving linear equations
a = np.array([
    [2,3],
    [4,1]
])
b = np.array([6,7])
x,y = np.linalg.solve(a,b) #2x+3y = 6, 4x+y = 7
print(x,y)

1.5 1.0


In [8]:
a = np.array([
    [2,1,1],
    [1,2,1],
    [1,1,2]
])
b = np.array([10,11,12])
x,y,z = np.linalg.solve(a,b)
print(x,y,z)

1.75 2.75 3.7499999999999996


In [14]:
#trace of a matrix = sum of all main diagonal elemenets
import numpy as np
a = np.random.randint(1,9,size=(2,2))
print(a)
trace = np.trace(a)
print(trace)

[[1 7]
 [3 8]]
9


In [11]:
import numpy as np
a = np.random.randint(2,9,size=(2,2))
print(a)
s = np.sum(np.diag(a))
print(s)

[[4 6]
 [6 7]]
11


In [18]:
import numpy as np
a = np.random.randint(2,9,size=(3,3))
print(a)
det = np.linalg.det(a)
print(det)

[[5 6 4]
 [4 6 3]
 [6 3 6]]
2.9999999999999996


In [73]:
import numpy as np
a = np.random.randint(2,9,size=(3,3))
print(a)
inv = np.linalg.inv(a).astype(int)
print(inv)

[[5 4 4]
 [7 7 4]
 [8 4 5]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [75]:
a = np.array([1,2,3,0,1,4,5,6,0]).reshape(3,3)
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)
print((a@a_inv).astype(int))

[[1 2 3]
 [0 1 4]
 [5 6 0]]
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [36]:
#saving nd array data
import numpy as np
a = np.random.randint(2,9,size=(3,3))
print(a)
np.savetxt(r"C:\Users\yaswa\Downloads\data.txt",a)
print("Data Saved")


[[3 6 3]
 [8 8 6]
 [7 5 4]]
Data Saved


In [43]:
b = np.loadtxt(r"C:\Users\yaswa\Downloads\data.txt")
c = b.astype(int)
print(c,type(c))

[[3 6 3]
 [8 8 6]
 [7 5 4]] <class 'numpy.ndarray'>


In [37]:
#saving nd array data
import numpy as np
a = np.random.randint(2,9,size=(3,3))
print(a)
np.save(r"C:\Users\yaswa\Downloads\data.npy",a)
print("Data Saved")



[[7 3 8]
 [8 2 5]
 [4 5 7]]
Data Saved


In [39]:
b = np.load(r"C:\Users\yaswa\Downloads\data.npy")
print(b,type(b))

[[7 3 8]
 [8 2 5]
 [4 5 7]] <class 'numpy.ndarray'>


In [46]:
#to save more than one nd array object --- using savez()
import numpy as np
a = np.random.randint(1,10,9)
b = np.random.randint(1,10,size=(3,3))
print(a)
print(b)
np.savez(r"C:\Users\yaswa\Downloads\data.npz",a,b)
print("Data Saved")

[3 5 9 1 8 2 4 2 5]
[[2 4 6]
 [6 3 1]
 [4 7 2]]
Data Saved


In [47]:
c = np.load(r"C:\Users\yaswa\Downloads\data.npz")
print(c.files)
print(c["arr_0"])
print(c["arr_1"])

['arr_0', 'arr_1']
[3 5 9 1 8 2 4 2 5]
[[2 4 6]
 [6 3 1]
 [4 7 2]]


In [56]:
#saving multiple nd arrays using savez
a = np.random.randint(1,10,9)
b = np.random.randint(1,10,size=(3,3))
c = np.random.randint(1,10,size=(3,3,3))
print(a)
print(b)
print(c)
np.savez(r"data.npz",a=a,b=b,c=c)
print("Data Saved")

[8 3 5 7 7 5 3 2 6]
[[4 1 3]
 [1 9 2]
 [1 1 6]]
[[[6 9 7]
  [1 6 7]
  [9 6 7]]

 [[5 3 4]
  [2 4 9]
  [6 9 7]]

 [[7 8 2]
  [8 7 6]
  [9 9 1]]]
Data Saved


In [57]:
#loading savez files
npzfile = np.load("data.npz")
print(npzfile.files)
print(npzfile["a"])
print(npzfile["b"])
print(npzfile["c"])

['a', 'b', 'c']
[8 3 5 7 7 5 3 2 6]
[[4 1 3]
 [1 9 2]
 [1 1 6]]
[[[6 9 7]
  [1 6 7]
  [9 6 7]]

 [[5 3 4]
  [2 4 9]
  [6 9 7]]

 [[7 8 2]
  [8 7 6]
  [9 9 1]]]


In [54]:
#savez_compressed
a = np.random.randint(1,10,9)
b = np.random.randint(1,10,size=(3,3))
np.savez_compressed(r"data.npz",a=a,b=b)
print("Data Saved")

Data Saved


In [55]:
#opening savez_compressed files
c = np.load(r"data.npz")
print(c.files)
print(c["a"])
print(c["b"])

['a', 'b']
[2 3 8 6 4 8 4 8 5]
[[1 3 4]
 [6 3 2]
 [5 6 7]]
